// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllIPv4Interfaces():Promise<Array<string>>;

export function GetDefaulOutboundIP():Promise<string>;

export function GetIPInfo(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;
