// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllIPv4Interfaces() {
  return window['go']['main']['App']['GetAllIPv4Interfaces']();
}

export function GetDefaulOutboundIP() {
  return window['go']['main']['App']['GetDefaulOutboundIP']();
}

export function GetIPInfo(arg1) {
  return window['go']['main']['App']['GetIPInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
